[package]
name = "moonmonkey_token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.7"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }

